import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
  client: {
    NEXT_PUBLIC_APP_URL: z.string().min(1),
    NEXT_PUBLIC_API_URL: z.string().url(),
    NEXT_PUBLIC_MASTERMODULES_URL: z.string().url(),
    NEXT_PUBLIC_SMOOTH_SWIPE_URL: z.string().url(),
    NEXT_PUBLIC_PUBLISH_IMAGE_URL: z.string().url(),
    NEXT_PUBLIC_ORDERIFIC_WEBSOCKET_KEY: z.string(),
    NEXT_PUBLIC_ORDERIFIC_WEBSOCKET_HOST: z.string(),
    NEXT_PUBLIC_INTERNETCASH_WEBSOCKET_KEY: z.string(),
    NEXT_PUBLIC_INTERNETCASH_WEBSOCKET_HOST: z.string(),
    NEXT_PUBLIC_INTERNETCASH_URL: z.string(),
  },
  runtimeEnv: {
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
    NEXT_PUBLIC_MASTERMODULES_URL: process.env.NEXT_PUBLIC_MASTERMODULES_URL,
    NEXT_PUBLIC_SMOOTH_SWIPE_URL: process.env.NEXT_PUBLIC_SMOOTH_SWIPE_URL,
    NEXT_PUBLIC_PUBLISH_IMAGE_URL: process.env.NEXT_PUBLIC_PUBLISH_IMAGE_URL,
    NEXT_PUBLIC_ORDERIFIC_WEBSOCKET_KEY:
      process.env.NEXT_PUBLIC_ORDERIFIC_WEBSOCKET_KEY,
    NEXT_PUBLIC_ORDERIFIC_WEBSOCKET_HOST:
      process.env.NEXT_PUBLIC_ORDERIFIC_WEBSOCKET_HOST,
    NEXT_PUBLIC_INTERNETCASH_URL: process.env.NEXT_PUBLIC_INTERNETCASH_URL,
    NEXT_PUBLIC_INTERNETCASH_WEBSOCKET_KEY:
      process.env.NEXT_PUBLIC_INTERNETCASH_WEBSOCKET_KEY,
    NEXT_PUBLIC_INTERNETCASH_WEBSOCKET_HOST:
      process.env.NEXT_PUBLIC_INTERNETCASH_WEBSOCKET_HOST,
  },
})
